import { Cable, Wrench, LayoutGrid, Flame, Cpu, Gauge, Zap, FileText, BatteryCharging, Network } from "lucide-react";

export const services = [
  {
    slug: "instalacoes-eletricas",
    icon: Cable,
    title: "Instalações Elétricas",
    summary: "Execução de instalações elétricas residenciais, comerciais, prediais e industriais, seguindo critérios técnicos de segurança e qualidade.",
    items: [
      "Instalações elétricas novas e reformas",
      "Montagem de infraestrutura elétrica",
      "Passagem de cabos e circuitos",
      "Instalação, retrofit e quadros elétricos",
      "Circuitos para máquinas, bombas, motores e equipamentos especiais",
      "Adequação de instalações antigas",
    ],
  },
  {
    slug: "manutencao-eletrica",
    icon: Wrench,
    title: "Manutenção Elétrica Preventiva e Corretiva",
    summary: "Atendimento técnico para identificação de falhas, correção de problemas elétricos e melhoria da segurança das instalações.",
    items: [
      "Correção de curto-circuito e falhas elétricas",
      "Substituição de disjuntores, DR, DPS, contatores e relés",
      "Reaperto e inspeção de conexões",
      "Correção de aquecimento em cabos e painéis",
      "Manutenção em quadros de distribuição",
      "Atendimento para condomínios, empresas e indústrias",
    ],
  },
  {
    slug: "paineis-eletricos",
    icon: LayoutGrid,
    title: "Montagem de Painéis Elétricos",
    summary: "Desenvolvimento e montagem de painéis de comando, potência, automação e proteção conforme a aplicação dedicada.",
    items: [
      "Painel de comando e potência",
      "Painel para bombas",
      "Partida direta e estrela-triângulo",
      "Painel com inversor de frequência ou soft-starter",
      "Banco de capacitores",
      "Organização, identificação e adequação de painéis existentes",
    ],
  },
  {
    slug: "alarme-incendio",
    icon: Flame,
    title: "Sistemas de Alarme de Incêndio",
    summary: "Instalação, manutenção e adequação de sistemas de alarme de incêndio convencionais e endereçáveis.",
    items: [
      "Central de alarme de incêndio",
      "Detectores de fumaça",
      "Acionadores manuais",
      "Sirenes audiovisuais",
      "Sistemas convencionais e endereçáveis",
      "Infraestrutura, testes e manutenção preventiva/corretiva",
    ],
  },
  {
    slug: "automacao",
    icon: Cpu,
    title: "Automação Elétrica e Industrial",
    summary: "Soluções para controle, monitoramento e acionamento de equipamentos, aumentando confiabilidade e eficiência operacional.",
    items: [
      "Automação de bombas",
      "Automação de painéis elétricos",
      "Controle de nível de reservatórios",
      "Acionamento automático de motores",
      "Programação de CLP",
    ],
  },
  {
    slug: "bombas-motores",
    icon: Gauge,
    title: "Bombas, Motores e Comandos",
    summary: "Instalação, manutenção e automação de sistemas com bombas, motores elétricos e comandos de acionamento.",
    items: [
      "Comando para bomba de recalque, incêndio e poço",
      "Sistema automático por boia ou sensor de nível",
      "Acionamento por inversor de frequência",
      "Proteção contra falta de fase, sobrecarga e curto-circuito",
      "Diagnóstico de falhas em motores",
      "Manutenção em painéis de bombas",
    ],
  },
  {
    slug: "spda-aterramento",
    icon: Zap,
    title: "SPDA e Aterramento",
    summary: "Inspeção, projeto, manutenção e adequação de sistemas de proteção contra descargas atmosféricas e aterramento elétrico.",
    items: [
      "Inspeção de captores, descidas e aterramento",
      "Medição de resistência de aterramento",
      "Manutenção de malhas de aterramento",
      "Adequação de sistemas existentes",
      "Emissão de relatório técnico",
      "Identificação de não conformidades",
    ],
  },
  {
    slug: "laudos",
    icon: FileText,
    title: "Laudos, Relatórios e Pareceres Técnicos",
    summary: "Documentos técnicos para auxiliar clientes na tomada de decisão, adequação normativa e manutenção das instalações.",
    items: [
      "Parecer técnico elétrico",
      "Relatório de inspeção",
      "Relatório de SPDA",
      "Relatório de manutenção elétrica",
      "Levantamento de não conformidades",
      "Registro fotográfico técnico e recomendações de adequação",
    ],
  },
  {
    slug: "banco-capacitores",
    icon: BatteryCharging,
    title: "Banco de Capacitores e Fator de Potência",
    summary: "Projeto, montagem, instalação e manutenção de bancos de capacitores, com análise técnica da instalação.",
    items: [
      "Banco de capacitores automático",
      "Banco com reator dessintonizado",
      "Correção de fator de potência",
      "Análise de energia",
      "Dimensionamento de etapas",
      "Manutenção em bancos existentes",
    ],
  },
  {
    slug: "infraestrutura",
    icon: Network,
    title: "Infraestrutura Elétrica",
    summary: "Execução de infraestrutura elétrica aparente e embutida para instalações comerciais, industriais e prediais.",
    items: [
      "Eletrodutos galvanizados",
      "Eletrocalhas, perfilados e leitos para cabos",
      "Caixas de passagem e conduletes",
      "Infraestrutura para alarme de incêndio",
      "Infraestrutura para automação",
      "Infraestrutura para máquinas e equipamentos",
    ],
  },
] as const;
